### ISSUE TITLE
Episode order is important

### ISSUE THREAD

**Issue by awendland** [treyfortmuller/tng_chooser#1]
You should really be watching these in order, otherwise you'll miss out on critical character arcs.

![image](https://user-images.githubusercontent.com/1152104/52924693-c2ecf500-32fb-11e9-8d82-23daa4f5a551.png)

**Comment by treyfortmuller** [comment]
Usage of these script is only recommended for fans of TNG with at least 3 watches of the entire series under their belt. The development team highly discourages usage for first-time TNG viewers. v1.0 is up and running enjoy.
